baseURL = "http://whitakerlab.github.io/"
languageCode = "en-gb"
title = "Whitaker Lab"
theme = "minimo"
enableEmoji = true

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

[params.info]
description = "Updates from Kirstie's research group"
title404 = "Sorry, but the page you were trying to view does not exist!"

[params.sidebar]
enable = true

[params.widgets]
sidebar = ["about", "search", "sidebar_menu", "social_menu"]

[params.social]
github = "WhitakerLab"
twitter = "Whitaker_Lab"

[[menu.main]]
name = "Home"
weight = 100
identifier = "home"
url = "/"

[[menu.main]]
name = "About"
weight = 200
identifier = "about"
url = "/about/"

[[menu.main]]
name = "Visit"
weight = 300
identifier = "visit"
url = "/visit/"

[[menu.main]]
name = "Contact"
weight = 400
identifier = "contact"
url = "/contact/"

[[menu.main]]
name = "GitHub"
weight = 500
identifier = "repository"
url = "https://github.com/whitakerlab"
